### ISSUE TITLE
Crash occurs while trying to craft custom storage disk

### ISSUE THREAD

**Issue by Azruine** [JavaPowerFR/StorageTech#8] opened 2020-12-19 21:46 UTC
The game crashes if I try to place mouse cursor on the result item.

Following is crash report.

https://pastebin.com/6WP3PC1B

**Comment by JavaPowerFR** [comment] 2020-12-23 09:38
Hi, the issue is fixed now.
thanks you.

**Closed as completed by JavaPowerFR** 2020-12-23 09:38 UTC
